id: IB0315BEA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T00:25:40+00:00'
last_modified: '2022-06-14T07:56:05.664677+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22084
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  author: ''
  base:
    BFEB:
      image_group_id: I0886
      title: ''
      total_pages: ''
      order: 1
      base_file: BFEB.txt
    B8D8:
      image_group_id: I0887
      title: ''
      total_pages: ''
      order: 2
      base_file: B8D8.txt
    D601:
      image_group_id: I0888
      title: ''
      total_pages: ''
      order: 3
      base_file: D601.txt
    04A3:
      image_group_id: I0889
      title: ''
      total_pages: ''
      order: 4
      base_file: 04A3.txt
    6CC3:
      image_group_id: I0890
      title: ''
      total_pages: ''
      order: 5
      base_file: 6CC3.txt
    D46C:
      image_group_id: I0891
      title: ''
      total_pages: ''
      order: 6
      base_file: D46C.txt
    F0EF:
      image_group_id: I0892
      title: ''
      total_pages: ''
      order: 7
      base_file: F0EF.txt
    30C8:
      image_group_id: I0893
      title: ''
      total_pages: ''
      order: 8
      base_file: 30C8.txt
    AA44:
      image_group_id: I0894
      title: ''
      total_pages: ''
      order: 9
      base_file: AA44.txt
    8A70:
      image_group_id: I0895
      title: ''
      total_pages: ''
      order: 10
      base_file: 8A70.txt
    '1209':
      image_group_id: I0896
      title: ''
      total_pages: ''
      order: 11
      base_file: 1209.txt
    6AC3:
      image_group_id: I0897
      title: ''
      total_pages: ''
      order: 12
      base_file: 6AC3.txt
    CDC6:
      image_group_id: I0898
      title: ''
      total_pages: ''
      order: 13
      base_file: CDC6.txt
    E9C4:
      image_group_id: I0899
      title: ''
      total_pages: ''
      order: 14
      base_file: E9C4.txt
    '4262':
      image_group_id: I0900
      title: ''
      total_pages: ''
      order: 15
      base_file: 4262.txt
    66E0:
      image_group_id: I0901
      title: ''
      total_pages: ''
      order: 16
      base_file: 66E0.txt
    FA95:
      image_group_id: I0902
      title: ''
      total_pages: ''
      order: 17
      base_file: FA95.txt
    C086:
      image_group_id: I0903
      title: ''
      total_pages: ''
      order: 18
      base_file: C086.txt
    '9095':
      image_group_id: I0904
      title: ''
      total_pages: ''
      order: 19
      base_file: 9095.txt
    C9D1:
      image_group_id: I0905
      title: ''
      total_pages: ''
      order: 20
      base_file: C9D1.txt
    2D77:
      image_group_id: I0906
      title: ''
      total_pages: ''
      order: 21
      base_file: 2D77.txt
    641A:
      image_group_id: I0907
      title: ''
      total_pages: ''
      order: 22
      base_file: 641A.txt
    469C:
      image_group_id: I0908
      title: ''
      total_pages: ''
      order: 23
      base_file: 469C.txt
    '4870':
      image_group_id: I0909
      title: ''
      total_pages: ''
      order: 24
      base_file: 4870.txt
    D404:
      image_group_id: I0910
      title: ''
      total_pages: ''
      order: 25
      base_file: D404.txt
    6A97:
      image_group_id: I0911
      title: ''
      total_pages: ''
      order: 26
      base_file: 6A97.txt
    ED85:
      image_group_id: I0912
      title: ''
      total_pages: ''
      order: 27
      base_file: ED85.txt
    8C53:
      image_group_id: I0913
      title: ''
      total_pages: ''
      order: 28
      base_file: 8C53.txt
    EE56:
      image_group_id: I0914
      title: ''
      total_pages: ''
      order: 29
      base_file: EE56.txt
    D0C3:
      image_group_id: I0915
      title: ''
      total_pages: ''
      order: 30
      base_file: D0C3.txt
    9AF3:
      image_group_id: I0916
      title: ''
      total_pages: ''
      order: 31
      base_file: 9AF3.txt
    64B5:
      image_group_id: I0917
      title: ''
      total_pages: ''
      order: 32
      base_file: 64B5.txt
    DAAE:
      image_group_id: I0918
      title: ''
      total_pages: ''
      order: 33
      base_file: DAAE.txt
    2A96:
      image_group_id: I0919
      title: ''
      total_pages: ''
      order: 34
      base_file: 2A96.txt
    '8445':
      image_group_id: I0920
      title: ''
      total_pages: ''
      order: 35
      base_file: 8445.txt
    6C8C:
      image_group_id: I0921
      title: ''
      total_pages: ''
      order: 36
      base_file: 6C8C.txt
    D1A0:
      image_group_id: I0922
      title: ''
      total_pages: ''
      order: 37
      base_file: D1A0.txt
    82D4:
      image_group_id: I0923
      title: ''
      total_pages: ''
      order: 38
      base_file: 82D4.txt
    EA5B:
      image_group_id: I0924
      title: ''
      total_pages: ''
      order: 39
      base_file: EA5B.txt
    CE4E:
      image_group_id: I0925
      title: ''
      total_pages: ''
      order: 40
      base_file: CE4E.txt
    4E49:
      image_group_id: I0926
      title: ''
      total_pages: ''
      order: 41
      base_file: 4E49.txt
    778E:
      image_group_id: I0927
      title: ''
      total_pages: ''
      order: 42
      base_file: 778E.txt
    F3A2:
      image_group_id: I0928
      title: ''
      total_pages: ''
      order: 43
      base_file: F3A2.txt
    45EA:
      image_group_id: I0929
      title: ''
      total_pages: ''
      order: 44
      base_file: 45EA.txt
    CCBB:
      image_group_id: I0930
      title: ''
      total_pages: ''
      order: 45
      base_file: CCBB.txt
    E474:
      image_group_id: I0931
      title: ''
      total_pages: ''
      order: 46
      base_file: E474.txt
    1FCC:
      image_group_id: I0932
      title: ''
      total_pages: ''
      order: 47
      base_file: 1FCC.txt
    F7CF:
      image_group_id: I0933
      title: ''
      total_pages: ''
      order: 48
      base_file: F7CF.txt
    64F7:
      image_group_id: I0934
      title: ''
      total_pages: ''
      order: 49
      base_file: 64F7.txt
    A9D7:
      image_group_id: I0935
      title: ''
      total_pages: ''
      order: 50
      base_file: A9D7.txt
    452A:
      image_group_id: I0936
      title: ''
      total_pages: ''
      order: 51
      base_file: 452A.txt
    '5459':
      image_group_id: I0937
      title: ''
      total_pages: ''
      order: 52
      base_file: 5459.txt
    FB82:
      image_group_id: I0938
      title: ''
      total_pages: ''
      order: 53
      base_file: FB82.txt
    '6041':
      image_group_id: I0939
      title: ''
      total_pages: ''
      order: 54
      base_file: 6041.txt
    C16D:
      image_group_id: I0940
      title: ''
      total_pages: ''
      order: 55
      base_file: C16D.txt
    05B9:
      image_group_id: I0941
      title: ''
      total_pages: ''
      order: 56
      base_file: 05B9.txt
    AFFC:
      image_group_id: I0942
      title: ''
      total_pages: ''
      order: 57
      base_file: AFFC.txt
    F1AF:
      image_group_id: I0943
      title: ''
      total_pages: ''
      order: 58
      base_file: F1AF.txt
    3EC9:
      image_group_id: I0944
      title: ''
      total_pages: ''
      order: 59
      base_file: 3EC9.txt
    487C:
      image_group_id: I0945
      title: ''
      total_pages: ''
      order: 60
      base_file: 487C.txt
    '4554':
      image_group_id: I0946
      title: ''
      total_pages: ''
      order: 61
      base_file: 4554.txt
    4CAC:
      image_group_id: I0947
      title: ''
      total_pages: ''
      order: 62
      base_file: 4CAC.txt
    8B4B:
      image_group_id: I0948
      title: ''
      total_pages: ''
      order: 63
      base_file: 8B4B.txt
    3A48:
      image_group_id: I0949
      title: ''
      total_pages: ''
      order: 64
      base_file: 3A48.txt
    7B65:
      image_group_id: I0950
      title: ''
      total_pages: ''
      order: 65
      base_file: 7B65.txt
    3EA1:
      image_group_id: I0951
      title: ''
      total_pages: ''
      order: 66
      base_file: 3EA1.txt
    654E:
      image_group_id: I0952
      title: ''
      total_pages: ''
      order: 67
      base_file: 654E.txt
    472F:
      image_group_id: I0953
      title: ''
      total_pages: ''
      order: 68
      base_file: 472F.txt
    FE30:
      image_group_id: I0954
      title: ''
      total_pages: ''
      order: 69
      base_file: FE30.txt
    '4708':
      image_group_id: I0955
      title: ''
      total_pages: ''
      order: 70
      base_file: 4708.txt
    438E:
      image_group_id: I0956
      title: ''
      total_pages: ''
      order: 71
      base_file: 438E.txt
    '5703':
      image_group_id: I0957
      title: ''
      total_pages: ''
      order: 72
      base_file: 5703.txt
    FC52:
      image_group_id: I0958
      title: ''
      total_pages: ''
      order: 73
      base_file: FC52.txt
    FB3A:
      image_group_id: I0959
      title: ''
      total_pages: ''
      order: 74
      base_file: FB3A.txt
    '8674':
      image_group_id: I0960
      title: ''
      total_pages: ''
      order: 75
      base_file: 8674.txt
    C8DA:
      image_group_id: I0961
      title: ''
      total_pages: ''
      order: 76
      base_file: C8DA.txt
    F174:
      image_group_id: I0962
      title: ''
      total_pages: ''
      order: 77
      base_file: F174.txt
    46BB:
      image_group_id: I0963
      title: ''
      total_pages: ''
      order: 78
      base_file: 46BB.txt
    2EF9:
      image_group_id: I0964
      title: ''
      total_pages: ''
      order: 79
      base_file: 2EF9.txt
    40EC:
      image_group_id: I0965
      title: ''
      total_pages: ''
      order: 80
      base_file: 40EC.txt
    3ECC:
      image_group_id: I0966
      title: ''
      total_pages: ''
      order: 81
      base_file: 3ECC.txt
    70C2:
      image_group_id: I0967
      title: ''
      total_pages: ''
      order: 82
      base_file: 70C2.txt
    BC5A:
      image_group_id: I0968
      title: ''
      total_pages: ''
      order: 83
      base_file: BC5A.txt
    D451:
      image_group_id: I0969
      title: ''
      total_pages: ''
      order: 84
      base_file: D451.txt
    E0AF:
      image_group_id: I0970
      title: ''
      total_pages: ''
      order: 85
      base_file: E0AF.txt
    6E54:
      image_group_id: I0971
      title: ''
      total_pages: ''
      order: 86
      base_file: 6E54.txt
    B82C:
      image_group_id: I0972
      title: ''
      total_pages: ''
      order: 87
      base_file: B82C.txt
    CE91:
      image_group_id: I0973
      title: ''
      total_pages: ''
      order: 88
      base_file: CE91.txt
    498A:
      image_group_id: I0974
      title: ''
      total_pages: ''
      order: 89
      base_file: 498A.txt
    412D:
      image_group_id: I0975
      title: ''
      total_pages: ''
      order: 90
      base_file: 412D.txt
    77DB:
      image_group_id: I0976
      title: ''
      total_pages: ''
      order: 91
      base_file: 77DB.txt
    777D:
      image_group_id: I0977
      title: ''
      total_pages: ''
      order: 92
      base_file: 777D.txt
    B0A8:
      image_group_id: I0978
      title: ''
      total_pages: ''
      order: 93
      base_file: B0A8.txt
    80AE:
      image_group_id: I0979
      title: ''
      total_pages: ''
      order: 94
      base_file: 80AE.txt
    2B46:
      image_group_id: I0980
      title: ''
      total_pages: ''
      order: 95
      base_file: 2B46.txt
    96A0:
      image_group_id: I0981
      title: ''
      total_pages: ''
      order: 96
      base_file: 96A0.txt
    06B0:
      image_group_id: I0982
      title: ''
      total_pages: ''
      order: 97
      base_file: 06B0.txt
    C110:
      image_group_id: I0983
      title: ''
      total_pages: ''
      order: 98
      base_file: C110.txt
    7F52:
      image_group_id: I0984
      title: ''
      total_pages: ''
      order: 99
      base_file: 7F52.txt
    11D4:
      image_group_id: I0985
      title: ''
      total_pages: ''
      order: 100
      base_file: 11D4.txt
    4BC3:
      image_group_id: I0986
      title: ''
      total_pages: ''
      order: 101
      base_file: 4BC3.txt
    7A7B:
      image_group_id: I0987
      title: ''
      total_pages: ''
      order: 102
      base_file: 7A7B.txt
    '8506':
      image_group_id: I0988
      title: ''
      total_pages: ''
      order: 103
      base_file: 8506.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
